In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import os
from matplotlib.pylab import rcParams
rcParams['figure.figsize'] = 20,10
import warnings
warnings.filterwarnings('ignore')

In [2]:
os.chdir('C:\\Users\\DELL\\Desktop\\TOPMENTOR\\Batch 84 Day 34\\')

In [3]:
os.getcwd()

'C:\\Users\\DELL\\Desktop\\TOPMENTOR\\Batch 84 Day 34'

In [4]:
df = pd.read_csv ('Solar Data Set.csv')

display (df)

Date  Solar Ir 
0        1/1/2019 0:00        0.0
1        1/1/2019 1:00        0.0
2        1/1/2019 2:00        0.0
3        1/1/2019 3:00        0.0
4        1/1/2019 4:00        0.0
...                ...        ...
8755  12/31/2019 19:00        0.0
8756  12/31/2019 20:00        0.0
8757  12/31/2019 21:00        0.0
8758  12/31/2019 22:00        0.0
8759  12/31/2019 23:00        0.0

[8760 rows x 2 columns]

In [5]:
display (df.shape )

(8760, 2)

In [6]:
df.dropna(inplace=True)

In [7]:
display (df.shape )

(8760, 2)

In [8]:
training_set = df.iloc[:8712,1:2].values
training_set 

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [9]:
training_set = df.iloc[:8712,1:2].values

test_set = df.iloc[8712:,1:2].values

display (training_set.shape)
display (test_set.shape)

(8712, 1)

(48, 1)

In [10]:
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range = (0,1))

training_set_scaled = sc.fit_transform(training_set)
test_set_scaled = sc.fit_transform(test_set)

In [12]:
X_train = []   #Empty list 
y_train = []
WS = 24 # 

In [13]:
for i in range(WS, len(training_set_scaled)):
    X_train.append(training_set_scaled[i-WS:i, 0:1])
    y_train.append(training_set_scaled[i, 0])

In [14]:
X_train

[array([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.08825763],
        [0.5036841 ],
        [0.73535219],
        [0.85436419],
        [0.88684977],
        [0.84271909],
        [0.70919407],
        [0.45698482],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]]),
 array([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.08825763],
        [0.5036841 ],
        [0.73535219],
        [0.85436419],
        [0.88684977],
        [0.84271909],
        [0.70919407],
        [0.45698482],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [15]:
y_train[0]

0.0

In [16]:
print  ('X Train Length ', len( X_train))
print ('Y Train Length ',len (y_train))

X Train Length  8688
Y Train Length  8688


In [17]:
X_train

[array([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.08825763],
        [0.5036841 ],
        [0.73535219],
        [0.85436419],
        [0.88684977],
        [0.84271909],
        [0.70919407],
        [0.45698482],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ]]),
 array([[0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.08825763],
        [0.5036841 ],
        [0.73535219],
        [0.85436419],
        [0.88684977],
        [0.84271909],
        [0.70919407],
        [0.45698482],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        [0.        ],
        

In [18]:
display (pd.DataFrame(X_train.reshape (8688,24)))

AttributeError: 'list' object has no attribute 'reshape'

In [19]:
X_train, y_train = np.array(X_train), np.array(y_train)
display (X_train.shape)
display (y_train.shape)

(8688, 24, 1)

(8688,)

In [20]:
X_train

array([[[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       ...,

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [0.]]])

In [21]:
display (pd.DataFrame(X_train.reshape (8688,24)))

0    1    2    3         4         5         6         7         8   \
0     0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.088258   
1     0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000  0.088258  0.503684   
2     0.0  0.0  0.0  0.0  0.000000  0.000000  0.088258  0.503684  0.735352   
3     0.0  0.0  0.0  0.0  0.000000  0.088258  0.503684  0.735352  0.854364   
4     0.0  0.0  0.0  0.0  0.088258  0.503684  0.735352  0.854364  0.886850   
...   ...  ...  ...  ...       ...       ...       ...       ...       ...   
8683  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   
8684  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   
8685  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   
8686  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   
8687  0.0  0.0  0.0  0.0  0.000000  0.000000  0.000000  0.000000  0.000000   

            9   ...        14        15        16        17        18  \
0     0.503684  ...  0.709194  0.456985  0.000000  0.000000  0.000000   
1     0.735352  ...  0.456985  0.000000  0.000000  0.000000  0.000000   
2     0.854364  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
3     0.886850  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
4     0.842719  ...  0.000000  0.000000  0.000000  0.000000  0.000000   
...        ...  ...       ...       ...       ...       ...       ...   
8683  0.000000  ...  0.507068  0.736642  0.853666  0.884281  0.837817   
8684  0.000000  ...  0.736642  0.853666  0.884281  0.837817  0.701025   
8685  0.000000  ...  0.853666  0.884281  0.837817  0.701025  0.443209   
8686  0.000000  ...  0.884281  0.837817  0.701025  0.443209  0.000000   
8687  0.092855  ...  0.837817  0.701025  0.443209  0.000000  0.000000   

            19        20   21   22   23  
0     0.000000  0.000000  0.0  0.0  0.0  
1     0.000000  0.000000  0.0  0.0  0.0  
2     0.000000  0.000000  0.0  0.0  0.0  
3     0.000000  0.000000  0.0  0.0  0.0  
4     0.000000  0.000000  0.0  0.0  0.0  
...        ...       ...  ...  ...  ...  
8683  0.701025  0.443209  0.0  0.0  0.0  
8684  0.443209  0.000000  0.0  0.0  0.0  
8685  0.000000  0.000000  0.0  0.0  0.0  
8686  0.000000  0.000000  0.0  0.0  0.0  
8687  0.000000  0.000000  0.0  0.0  0.0  

[8688 rows x 24 columns]

In [22]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Dropout

ModuleNotFoundError: No module named 'keras'

In [23]:
Model_P = Sequential()

Model_P.add(LSTM(units = 60, return_sequences = True, input_shape = (X_train.shape[1],1)))

Model_P.add(Dropout(0.2))

NameError: name 'Sequential' is not defined